language: node_js

os:
  - osx
  - linux
  - windows

node_js:
  - 10
  - 12
  - node

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      os: osx
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
